import { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import Footer from "./components/Footer";
import { LanguageProvider } from "./context/LanguageContext";

interface IMetadata {
  title: string;
  description: string;
}

export const metadata: IMetadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LanguageProvider>
          <Navbar />
          <Sidebar />
          {children}
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
