import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import Footer from "./components/Footer";
import ClientLanguageProvider from "./ClientLanguageProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ClientLanguageProvider>
          <Navbar />
          <Sidebar />
          {children}
          <Footer />
        </ClientLanguageProvider>
      </body>
    </html>
  );
}
